package pl.gda.pg.eti.kask.soundmeterpg;

/**
 * Created by Daniel on 05.10.2016.
 */

public enum IntentActionsAndKeys {
    SAMPLE_RECEIVE_ACTION,
    END_ACTION_WORKING_BACKGROUND,
    SAMPLE_KEY ,
    END_ACTION,
    END_ACTION_SENDER,
    ERROR_MEASURE_ACTION,
    ERROR_KEY,
    GPS_ERROR_KEY,
    MICROPHONE_ERROR_KEY,
    GPS_INACCESSIBLE_KEY,
    GPS_TURN_OFF_KEY(),
    INTERNAL_UNKNOWN_ERROR,
    ON_BACKGROUND_END_ACTION,
    MEASUREMENT_STATISTICS_KEY,
    COUNTER_KEY;


}
